---
collections:
  - name: community.general
    version: ">=12.4.0,<12.5.0"
  - name: community.mongodb
    version: ">=1.7.10,<2.0.0"

roles:
  - name: rolehippie.mongodb
  - name: rolehippie.elasticsearch

...
