---
collections:
  - name: community.general
    version: ">=11.3.0,<12.0.0"
  - name: community.mongodb
    version: ">=1.7.10,<2.0.0"

roles:
  - name: rolehippie.mongodb
  - name: rolehippie.elasticsearch

...
