# Standards: 1.2
---
- name: Reload graylog-server
  systemd:
    name: graylog-server
    state: reloaded
    daemon_reload: True

- name: Restart graylog-server
  systemd:
    name: graylog-server
    state: restarted
    daemon_reload: True

- name: Restart graylog-oauth2
  systemd:
    name: graylog-oauth2
    state: restarted
    daemon_reload: yes

...
